"""empty message

Revision ID: 26dbfccc974b
Revises: 31a852d26988
Create Date: 2016-06-06 16:46:56.692000

"""

# revision identifiers, used by Alembic.
revision = '26dbfccc974b'
down_revision = '31a852d26988'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.Boolean(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('admin')

    ### end Alembic commands ###
