"""empty message

Revision ID: 31a852d26988
Revises: None
Create Date: 2016-06-05 22:22:42.852000

"""

# revision identifiers, used by Alembic.
revision = '31a852d26988'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_entry_slug'), ['slug'])
        batch_op.create_foreign_key(batch_op.f('fk_entry_author_id_user'), 'user', ['author_id'], ['id'])

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_tag_slug'), ['slug'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_slug'), ['slug'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_slug'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_tag_slug'), type_='unique')

    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_entry_author_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('uq_entry_slug'), type_='unique')

    ### end Alembic commands ###
